### ISSUE TITLE
Incorrect implementation of LDA (Latent Dirichlet Allocation)

### ISSUE THREAD

**Issue by CyxouD** [RamaneekGill/Twitter-Sentiment-Analysis#3]
You stated that LDA (Latent Dirichlet Allocation) algorithm is used, but actually LinearDiscriminantAnalysis class is not implementation of this algorithm. LatentDirichletAllocation should be used. Correct me if I am wrong if those implementations are both for the same algorithm, but description of them, particularly at sklearn docs, don't look like this

**Comment by RamaneekGill** [comment]
You're right! I must have mixed up my acronyms along the way...
